# Generated by Django 4.2.2 on 2023-06-20 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0)),
                ('first_name', models.CharField(default='Not stated', max_length=40)),
                ('middle_name', models.CharField(default='Not stated', max_length=40)),
                ('last_name', models.CharField(default='Not stated', max_length=40)),
                ('group', models.CharField(blank=True, choices=[('None', 'Другое'), ('Bi_T', 'Биология (Турчина Т.А.)'), ('Bi_S', 'Биология (Скороделова К.А.)'), ('Ch_K', 'Химия (Качалова Е.А.)'), ('Ch_R', 'Химия (Родионова Н.М.)'), ('IT_K', 'Информатика (Котова Д.А.)'), ('Fis1', 'Физика 1 (Шагалова А.А.)'), ('Fis2', 'Физика 2 (Грачёв А.А.)'), ('Fis3', 'Физика 3 (Дмитричева А.А.)'), ('Fis4', 'Физика 4 (Шевцова Т.Г.)')], default='None', help_text='Группа обучения', max_length=4)),
                ('party', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-balance'],
            },
        ),
    ]
