# Generated by Django 4.2.2 on 2023-06-20 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['party', '-balance'], 'permissions': (('staff_', 'Принадлежность к персоналу'), ('viewer_1', 'Может смотреть весь отряд: 1'), ('viewer_2', 'Может смотреть весь отряд: 2'), ('viewer_3', 'Может смотреть весь отряд: 3'), ('viewer_4', 'Может смотреть весь отряд: 4'), ('viewer_5', 'Может смотреть весь отряд: 5'), ('viewer_all', 'Может смотреть все отряды'), ('viewer', 'Может смотреть какой-то отряд'), ('pedagogue', 'Принадлежность к педагогам'))},
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('comment', models.CharField(default='Не указано', max_length=40)),
                ('sign', models.CharField(blank=True, choices=[('N', 'None'), ('+', '+'), ('-', '_')], default='N', help_text='Премия или штраф? + или -?', max_length=1)),
                ('cnt', models.FloatField(default=0)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.account')),
            ],
        ),
    ]
