# Generated by Django 4.2.2 on 2023-06-20 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_account_options_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='rool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, choices=[('U', 'Уголовный кодекс'), ('A', 'Административный кодекс'), ('T', 'Трудовой кодекс'), ('P', 'Кодекс премий'), ('N', 'None')], default='N', help_text='Тип закона', max_length=1)),
                ('num_pt2', models.IntegerField(default=1, help_text='Раздел кодекса')),
                ('num_pt3', models.IntegerField(default=0, help_text='Часть раздела')),
                ('comment', models.CharField(default='Не указано', max_length=140)),
                ('punishment', models.CharField(default='Не указано', max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='comment',
            field=models.CharField(default='Не указано', max_length=70),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime),
        ),
    ]
