# Generated by Django 4.2.2 on 2023-06-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_remove_rool_group_rool_num_pt1'),
    ]

    operations = [
        migrations.CreateModel(
            name='rule_a',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_pt1', models.IntegerField(default=1, help_text='Раздел кодекса')),
                ('num_pt2', models.IntegerField(default=0, help_text='Часть раздела')),
                ('comment', models.CharField(default='Не указано', max_length=140)),
                ('punishment', models.CharField(default='Не указано', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='rule_p',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_pt1', models.IntegerField(default=1, help_text='Раздел кодекса')),
                ('num_pt2', models.IntegerField(default=0, help_text='Часть раздела')),
                ('comment', models.CharField(default='Не указано', max_length=140)),
                ('punishment', models.CharField(default='Не указано', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='rule_t',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_pt1', models.IntegerField(default=1, help_text='Раздел кодекса')),
                ('num_pt2', models.IntegerField(default=0, help_text='Часть раздела')),
                ('comment', models.CharField(default='Не указано', max_length=140)),
                ('punishment', models.CharField(default='Не указано', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='rule_u',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_pt1', models.IntegerField(default=1, help_text='Раздел кодекса')),
                ('num_pt2', models.IntegerField(default=0, help_text='Часть раздела')),
                ('comment', models.CharField(default='Не указано', max_length=140)),
                ('punishment', models.CharField(default='Не указано', max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='rool',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sign',
            field=models.CharField(blank=True, choices=[('N', 'None'), ('+', '+'), ('-', '-')], default='N', help_text='Премия или штраф? + или -?', max_length=1),
        ),
    ]
