# Generated by Django 4.2.2 on 2023-06-21 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_rule_a_rule_p_rule_t_rule_u_delete_rool_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='subject',
            new_name='whose_account',
        ),
    ]
