# Generated by Django 4.2.2 on 2023-06-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_rename_subject_transaction_whose_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule_a',
            name='comment',
            field=models.CharField(default='Не указано', max_length=250),
        ),
        migrations.AlterField(
            model_name='rule_a',
            name='punishment',
            field=models.CharField(default='Не указано', max_length=100),
        ),
    ]
