# Generated by Django 4.2.2 on 2023-06-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_alter_rule_a_comment_alter_rule_a_punishment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule_p',
            name='comment',
            field=models.CharField(default='Не указано', max_length=250),
        ),
        migrations.AlterField(
            model_name='rule_p',
            name='punishment',
            field=models.CharField(default='Не указано', max_length=100),
        ),
        migrations.AlterField(
            model_name='rule_t',
            name='comment',
            field=models.CharField(default='Не указано', max_length=250),
        ),
        migrations.AlterField(
            model_name='rule_t',
            name='punishment',
            field=models.CharField(default='Не указано', max_length=100),
        ),
        migrations.AlterField(
            model_name='rule_u',
            name='comment',
            field=models.CharField(default='Не указано', max_length=250),
        ),
        migrations.AlterField(
            model_name='rule_u',
            name='punishment',
            field=models.CharField(default='Не указано', max_length=100),
        ),
    ]
