# Generated by Django 4.2.2 on 2023-06-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_alter_rule_p_comment_alter_rule_p_punishment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', help_text='Для удобства отображения счёта', max_length=140)),
                ('balance', models.FloatField(default=0)),
                ('sign', models.CharField(blank=True, choices=[('N', 'None'), ('+', 'Начислить'), ('-', 'Оштрафовать')], default='N', help_text='Если None, то непосредственно счёт пионера.', max_length=1)),
            ],
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['party', 'last_name'], 'permissions': (('staff_', 'Принадлежность к персоналу'), ('viewer_1', 'Может смотреть весь отряд: 1'), ('viewer_2', 'Может смотреть весь отряд: 2'), ('viewer_3', 'Может смотреть весь отряд: 3'), ('viewer_4', 'Может смотреть весь отряд: 4'), ('viewer_5', 'Может смотреть весь отряд: 5'), ('viewer_all', 'Может смотреть все отряды'), ('viewer', 'Может смотреть какой-то отряд'), ('pedagogue', 'Принадлежность к педагогам'))},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sign',
        ),
    ]
