# Generated by Django 4.2.2 on 2023-06-21 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_remove_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='name',
            field=models.OneToOneField(help_text='Выберите аккаунт, к которому привязан этот кошелёк.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.account'),
        ),
    ]
