# Generated by Django 4.2.2 on 2023-06-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0014_remove_transaction_whose_account_transaction_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='non_exit',
            field=models.BooleanField(default=True, help_text='Никогда не трогайте этот параметр, если транзакция не применена вручную, иначе поставьте значение True.'),
        ),
    ]
