# Generated by Django 4.2.2 on 2023-06-22 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0018_alter_transaction_name_alter_transaction_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='non_exit',
        ),
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='name',
            field=models.OneToOneField(help_text='Выберите кошелёк, откуда снимать (нужен Admin B.B.).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_from', to='bank.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiver',
            field=models.ForeignKey(help_text='Чей кошелёк оштрафован/премирован?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_to', to='bank.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sign',
            field=models.CharField(blank=True, choices=[('+', 'Начислить'), ('-', 'Оштрафовать')], default='+', max_length=1),
        ),
        migrations.DeleteModel(
            name='money',
        ),
    ]
