# Generated by Django 4.2.2 on 2023-06-22 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0019_remove_transaction_non_exit_account_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receiver',
            field=models.OneToOneField(help_text='Чей кошелёк оштрафован/премирован?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_to', to='bank.account'),
        ),
    ]
