# Generated by Django 4.2.2 on 2023-06-22 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0021_acc_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='acc_transaction',
        ),
    ]
