# Generated by Django 4.2.2 on 2023-06-22 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0022_delete_acc_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['party', 'last_name'], 'permissions': (('staff_', 'Принадлежность к персоналу'), ('viewer', 'Может смотреть какой-то отряд'), ('pedagogue', 'Принадлежность к педагогам'))},
        ),
    ]
