# Generated by Django 4.2.2 on 2023-06-22 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0023_alter_account_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['party', 'last_name'], 'permissions': (('staff_', 'Принадлежность к персоналу'), ('viewer', 'Может смотреть какой-то отряд'), ('pedagogue', 'Принадлежность к педагогам'), ('shop', 'Может смотреть магазин'))},
        ),
    ]
