# Generated by Django 4.2.2 on 2023-06-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0028_alter_account_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='receiver',
        ),
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.ManyToManyField(help_text='Выберите кошелёк, откуда снимать (нужен Admin B.B.).', related_name='account_from', to='bank.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receiver',
            field=models.ManyToManyField(help_text='Чей кошелёк оштрафован/премирован?', related_name='account_to', to='bank.account'),
        ),
    ]
