# Generated by Django 4.2.2 on 2023-06-23 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0029_remove_transaction_name_remove_transaction_receiver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='receiver',
        ),
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.ForeignKey(help_text='Выберите кошелёк, откуда снимать (нужен Admin B.B.).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_from', to='bank.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receiver',
            field=models.ForeignKey(help_text='Чей кошелёк оштрафован/премирован?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_to', to='bank.account'),
        ),
    ]
