# Generated by Django 4.2.2 on 2023-06-23 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0032_alter_account_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('comment', models.CharField(default='Не указано', max_length=70)),
                ('counted', models.BooleanField(default=False, editable=False)),
                ('sign', models.CharField(blank=True, choices=[('+', 'Начислить'), ('-', 'Оштрафовать')], default='+', max_length=1)),
                ('cnt', models.FloatField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_trans', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_trans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction_staff',
            name='name',
        ),
        migrations.DeleteModel(
            name='transaction_base',
        ),
        migrations.DeleteModel(
            name='transaction_staff',
        ),
    ]
