# Generated by Django 4.2.2 on 2023-06-23 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0034_remove_transaction_recipient_transaction_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_trans', to='bank.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
