# Generated by Django 4.2.2 on 2023-06-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0035_alter_transaction_creator_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='group',
            field=models.CharField(choices=[('None', 'Другое'), ('Bi_T', 'Биология (Турчина Т.А.)'), ('Bi_S', 'Биология (Скороделова К.А.)'), ('Ch_K', 'Химия (Качалова Е.А.)'), ('Ch_R', 'Химия (Родионова Н.М.)'), ('IT_K', 'Информатика (Котова Д.А.)'), ('Fis1', 'Физика 1 (Шагалова А.А.)'), ('Fis2', 'Физика 2 (Грачёв А.А.)'), ('Fis3', 'Физика 3 (Дмитричева А.А.)'), ('Fis4', 'Физика 4 (Шевцова Т.Г.)')], default='None', help_text='Группа обучения', max_length=4),
        ),
    ]
