# Generated by Django 4.2.2 on 2023-06-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0036_alter_account_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='cnt',
            field=models.FloatField(default=0),
        ),
    ]
