# Generated by Django 4.2.2 on 2023-06-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0037_alter_transaction_cnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='sign',
            field=models.CharField(choices=[('+', 'Начислить'), ('-', 'Оштрафовать')], default='+', max_length=1),
        ),
    ]
