# Generated by Django 4.2.2 on 2023-06-24 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0038_alter_transaction_sign'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['date']},
        ),
    ]
