# Generated by Django 4.2.2 on 2023-06-24 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0039_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date']},
        ),
    ]
