# Generated by Django 4.2.2 on 2023-06-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0041_alter_transaction_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('comment', models.CharField(default='', max_length=250)),
                ('cost', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-cost'],
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
